package rules

import (
	"os"
	"path/filepath"
	"testing"
)

func TestSTR01ConsistencyAcrossMethods(t *testing.T) {
	dir := t.TempDir()
	file := filepath.Join(dir, "sample.go")
	content := `package sample
type Client struct{}
func (c Client) Do() {}
func (cl Client) Reset() {}
`
	if err := os.WriteFile(file, []byte(content), 0o644); err != nil {
		t.Fatalf("write sample file: %v", err)
	}

	diags, err := NewSTR01().Run(Context{Files: []string{file}})
	if err != nil {
		t.Fatalf("run STR-01: %v", err)
	}
	if len(diags) == 0 {
		t.Fatalf("expected STR-01 diagnostics for inconsistent receiver names")
	}
}

func TestSTR02ForbiddenReceiverNames(t *testing.T) {
	dir := t.TempDir()
	file := filepath.Join(dir, "sample.go")
	content := `package sample
type Client struct{}
func (self *Client) Do() {}
`
	if err := os.WriteFile(file, []byte(content), 0o644); err != nil {
		t.Fatalf("write sample file: %v", err)
	}

	diags, err := NewSTR02().Run(Context{Files: []string{file}})
	if err != nil {
		t.Fatalf("run STR-02: %v", err)
	}
	if len(diags) != 1 {
		t.Fatalf("expected 1 STR-02 diagnostic, got %d", len(diags))
	}
}

func TestSTR03InterfaceException(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/str03\n\ngo 1.22\n"), 0o644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}
	content := `package sample
type Getter interface { Get() int }
type Client struct{}
func (c Client) Get() int { return 0 }
func (c Client) Set(v int) {}
`
	if err := os.WriteFile(filepath.Join(dir, "sample.go"), []byte(content), 0o644); err != nil {
		t.Fatalf("write sample file: %v", err)
	}

	diags, err := NewSTR03().Run(Context{Root: dir})
	if err != nil {
		t.Fatalf("run STR-03: %v", err)
	}
	if len(diags) != 1 {
		t.Fatalf("expected exactly 1 STR-03 warning for Set, got %d", len(diags))
	}
}

func TestSTR04SkipsGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/str04\n\ngo 1.22\n"), 0o644); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	mainFile := `package sample
type Point struct{ X, Y int }
var _ = Point{1, 2}
`
	if err := os.WriteFile(filepath.Join(dir, "sample.go"), []byte(mainFile), 0o644); err != nil {
		t.Fatalf("write sample file: %v", err)
	}

	genFile := `package sample
// Code generated by tool. DO NOT EDIT.
type Generated struct{ A, B int }
var _ = Generated{1, 2}
`
	if err := os.WriteFile(filepath.Join(dir, "sample.pb.go"), []byte(genFile), 0o644); err != nil {
		t.Fatalf("write generated file: %v", err)
	}

	diags, err := NewSTR04().Run(Context{Root: dir})
	if err != nil {
		t.Fatalf("run STR-04: %v", err)
	}
	if len(diags) != 1 {
		t.Fatalf("expected 1 STR-04 diagnostic from non-generated file, got %d", len(diags))
	}
}
