package rules

import (
	"os"
	"path/filepath"
	"testing"
)

const (
	strFileSampleGo = "sample.go"
	strFileGoMod    = "go.mod"
	strWriteErrFmt  = "write sample file: %v"
	strFilePerm     = 0o644
	strModule03     = "module example.com/str03\n\ngo 1.22\n"
	strModule04     = "module example.com/str04\n\ngo 1.22\n"
)

// TestSTR01ConsistencyAcrossMethods documents this exported function.
func TestSTR01ConsistencyAcrossMethods(t *testing.T) {
	dir := t.TempDir()
	file := filepath.Join(dir, strFileSampleGo)
	content := `package sample
// Client documents this exported type.
type Client struct{}
// Do documents this exported method.
func (c Client) Do() {}
// Reset documents this exported method.
func (cl Client) Reset() {}
`
	if err := os.WriteFile(file, []byte(content), strFilePerm); err != nil {
		t.Fatalf(strWriteErrFmt, err)
	}

	diags, err := NewSTR01().Run(Context{Files: []string{file}})
	if err != nil {
		t.Fatalf("run STR-01: %v", err)
	}
	if len(diags) == 0 {
		t.Fatalf("expected STR-01 diagnostics for inconsistent receiver names")
	}
}

// TestSTR02ForbiddenReceiverNames documents this exported function.
func TestSTR02ForbiddenReceiverNames(t *testing.T) {
	dir := t.TempDir()
	file := filepath.Join(dir, strFileSampleGo)
	content := `package sample
// Client documents this exported type.
type Client struct{}
// Do documents this exported method.
func (self *Client) Do() {}
`
	if err := os.WriteFile(file, []byte(content), strFilePerm); err != nil {
		t.Fatalf(strWriteErrFmt, err)
	}

	diags, err := NewSTR02().Run(Context{Files: []string{file}})
	if err != nil {
		t.Fatalf("run STR-02: %v", err)
	}
	if len(diags) != 1 {
		t.Fatalf("expected 1 STR-02 diagnostic, got %d", len(diags))
	}
}

// TestSTR03InterfaceException documents this exported function.
func TestSTR03InterfaceException(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, strFileGoMod), []byte(strModule03), strFilePerm); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}
	content := `package sample
// Getter documents this exported type.
type Getter interface { Get() int }
// Client documents this exported type.
type Client struct{}
// Get documents this exported method.
func (c Client) Get() int { return 0 }
// Set documents this exported method.
func (c Client) Set(v int) {}
`
	if err := os.WriteFile(filepath.Join(dir, strFileSampleGo), []byte(content), strFilePerm); err != nil {
		t.Fatalf(strWriteErrFmt, err)
	}

	diags, err := NewSTR03().Run(Context{Root: dir})
	if err != nil {
		t.Fatalf("run STR-03: %v", err)
	}
	if len(diags) != 1 {
		t.Fatalf("expected exactly 1 STR-03 warning for Set, got %d", len(diags))
	}
}

// TestSTR04SkipsGeneratedFiles documents this exported function.
func TestSTR04SkipsGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, strFileGoMod), []byte(strModule04), strFilePerm); err != nil {
		t.Fatalf("write go.mod: %v", err)
	}

	mainFile := `package sample
// Point documents this exported type.
type Point struct{ X, Y int }
var _ = Point{1, 2}
`
	if err := os.WriteFile(filepath.Join(dir, strFileSampleGo), []byte(mainFile), strFilePerm); err != nil {
		t.Fatalf(strWriteErrFmt, err)
	}

	genFile := `package sample
// Code generated by tool. DO NOT EDIT.
type Generated struct{ A, B int }
var _ = Generated{1, 2}
`
	if err := os.WriteFile(filepath.Join(dir, "sample.pb.go"), []byte(genFile), strFilePerm); err != nil {
		t.Fatalf("write generated file: %v", err)
	}

	diags, err := NewSTR04().Run(Context{Root: dir})
	if err != nil {
		t.Fatalf("run STR-04: %v", err)
	}
	if len(diags) != 1 {
		t.Fatalf("expected 1 STR-04 diagnostic from non-generated file, got %d", len(diags))
	}
}
