package rules

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeStructuralFile(t *testing.T, dir, name, content string) string {
	t.Helper()
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
	return path
}

func bodyWithNLines(n int) string {
	if n <= 0 {
		return ""
	}
	var builder strings.Builder
	for i := 0; i < n; i++ {
		builder.WriteString("\t_ = 0\n")
	}
	return builder.String()
}

func TestLIM01_FunctionLineLimits(t *testing.T) {
	tests := []struct {
		name      string
		source    string
		wantCount int
	}{
		{
			name:      "long func decl fails",
			source:    "package sample\nfunc f() {\n" + bodyWithNLines(51) + "}\n",
			wantCount: 1,
		},
		{
			name:      "long func literal fails independently",
			source:    "package sample\nfunc f() {\n\tg := func() {\n" + bodyWithNLines(51) + "\t}\n\t_ = g\n}\n",
			wantCount: 1,
		},
		{
			name:      "exactly 50 lines passes",
			source:    "package sample\nfunc f() {\n" + bodyWithNLines(50) + "}\n",
			wantCount: 0,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			file := writeStructuralFile(t, dir, "sample.go", tc.source)

			diags, err := NewLIM01().Run(Context{Files: []string{file}})
			if err != nil {
				t.Fatalf("run LIM-01: %v", err)
			}
			if len(diags) != tc.wantCount {
				t.Fatalf("expected %d diagnostics, got %d", tc.wantCount, len(diags))
			}
		})
	}
}

func TestLIM02_ParameterCounting(t *testing.T) {
	tests := []struct {
		name      string
		source    string
		wantCount int
	}{
		{
			name: "grouped parameters counted by names",
			source: `package sample
func f(a, b, c, d, e, f int) {}
`,
			wantCount: 1,
		},
		{
			name: "method receiver excluded",
			source: `package sample
type S struct{}
func (s S) f(a, b, c, d, e int) {}
`,
			wantCount: 0,
		},
		{
			name: "variadic counts as one",
			source: `package sample
func f(a, b, c, d int, rest ...string) {}
`,
			wantCount: 0,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			file := writeStructuralFile(t, dir, "sample.go", tc.source)

			diags, err := NewLIM02().Run(Context{Files: []string{file}})
			if err != nil {
				t.Fatalf("run LIM-02: %v", err)
			}
			if len(diags) != tc.wantCount {
				t.Fatalf("expected %d diagnostics, got %d", tc.wantCount, len(diags))
			}
		})
	}
}

func TestLIM03_NestingDepth(t *testing.T) {
	tests := []struct {
		name      string
		source    string
		wantAtMin int
	}{
		{
			name: "depth over four fails",
			source: `package sample
func f(a, b, c, d, e bool) {
	if a {
		for b {
			switch {
			case c:
				if d {
					if e {
						_ = 1
					}
				}
			}
		}
	}
}
`,
			wantAtMin: 1,
		},
		{
			name: "func literal resets depth",
			source: `package sample
func f(a, b, c, d bool) {
	if a {
		for b {
			g := func() {
				if c {
					if d {
						_ = 1
					}
				}
			}
			_ = g
		}
	}
}
`,
			wantAtMin: 0,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			file := writeStructuralFile(t, dir, "sample.go", tc.source)

			diags, err := NewLIM03().Run(Context{Files: []string{file}})
			if err != nil {
				t.Fatalf("run LIM-03: %v", err)
			}
			if len(diags) < tc.wantAtMin {
				t.Fatalf("expected at least %d diagnostics, got %d", tc.wantAtMin, len(diags))
			}
			if tc.wantAtMin == 0 && len(diags) != 0 {
				t.Fatalf("expected no diagnostics, got %d", len(diags))
			}
		})
	}
}

func TestLIM04_FileLength(t *testing.T) {
	tests := []struct {
		name      string
		filename  string
		source    string
		wantCount int
	}{
		{
			name:      "over 500 warns",
			filename:  "sample.go",
			source:    "package sample\n" + strings.Repeat("var _ = 1\n", 501),
			wantCount: 1,
		},
		{
			name:      "generated file skipped",
			filename:  "generated.pb.go",
			source:    "package sample\n// Code generated by tool. DO NOT EDIT.\n" + strings.Repeat("var _ = 1\n", 600),
			wantCount: 0,
		},
		{
			name:      "test file skipped",
			filename:  "sample_test.go",
			source:    "package sample\n" + strings.Repeat("var _ = 1\n", 600),
			wantCount: 0,
		},
		{
			name:      "trailing blanks ignored",
			filename:  "trim.go",
			source:    "package sample\n" + strings.Repeat("var _ = 1\n", 499) + "\n\n\n",
			wantCount: 0,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			file := writeStructuralFile(t, dir, tc.filename, tc.source)

			diags, err := NewLIM04().Run(Context{Files: []string{file}})
			if err != nil {
				t.Fatalf("run LIM-04: %v", err)
			}
			if len(diags) != tc.wantCount {
				t.Fatalf("expected %d diagnostics, got %d", tc.wantCount, len(diags))
			}
		})
	}
}
